//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Achat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Achat()
        {
            this.Bien = new HashSet<Bien>();
            this.Vehicule = new HashSet<Vehicule>();
        }

        public int Id_achat { get; set; }
        public int idDelegation { get; set; }
        public int Id_fournisseur { get; set; }
 
        [DataType(DataType.Date)]

        [Required(ErrorMessage = "La date de livraison est obligatoire")]
        public Nullable<System.DateTime> Date_livraison { get; set; }

        [Required(ErrorMessage = "Le champ N° de facture est obligatoire")]
        [Range(1, 999999, ErrorMessage = "Le numéro de la facture ne peut en contenir que 6 chiffre au maximum")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Le numéro de la facture est invalide")]
        [Column]
        public Nullable<int> Num_facture { get; set; }
        [Required(ErrorMessage = "Le champ N° de commande est obligatoire")]
        [Range(1, 999999, ErrorMessage = "Le numéro de commande ne peut en contenir que 6 chiffre au maximum")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Le numéro de commande est invalide")]
        [Column]
        public Nullable<int> Num_commande { get; set; }
        [DataType(DataType.Date)]
       
        [Required(ErrorMessage = "La date d'achat est obligatoire")]
        public Nullable<System.DateTime> Date_d_achat { get; set; }
        [Required(ErrorMessage = "Le prix d'achat est obligatoire")]
        [RegularExpression(@"[0-9]+([,][0-9]{0,3})?", ErrorMessage = "Le prix d'achat est invalid.Exemlpe: 20,000")]
        public Nullable<double> Prix_d_achat { get; set; }
        [Required(ErrorMessage = "Le N° de livraison est obligatoire")]
        [Range(1, 999999, ErrorMessage = "Le numéro de livraison ne peut en contenir que 6 chiffre au maximum")]
        [RegularExpression(@"^[0-9]+$", ErrorMessage = "Le numéro de livraison est invalide")]
        [Column]
        public Nullable<int> Num_livraison { get; set; }

        public virtual Fournisseur Fournisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bien> Bien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicule> Vehicule { get; set; }
    }
}
