//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bien()
        {
            this.InventaireBien = new HashSet<InventaireBien>();
            this.MouvementBien = new HashSet<MouvementBien>();
        }
    
        public Nullable<int> idBatiment { get; set; }
        public int Id_etage { get; set; }
        public Nullable<int> idDelegation { get; set; }
        public Nullable<int> IdDepot { get; set; }
        public int Id_bien { get; set; }
        public Nullable<int> Id_categorie { get; set; }
        public Nullable<int> Id_achat { get; set; }
        public Nullable<int> Id_service { get; set; }
        public Nullable<int> id { get; set; }
        public string Designation { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> Num_Serie { get; set; }
        public string Etat { get; set; }
        public string Valeur { get; set; }
        public string Mode { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Code_a_barre { get; set; }
        public string Emploi_principal { get; set; }
        public Nullable<System.DateTime> Date_d_installation { get; set; }
        public string Sous_categorie { get; set; }
        public string Modele { get; set; }
        public string Sous_Modele { get; set; }
        public string Marque { get; set; }
    
        public virtual Achat Achat { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual Depot Depot { get; set; }
        public virtual Etage Etage { get; set; }
        public virtual Personnel Personnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventaireBien> InventaireBien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MouvementBien> MouvementBien { get; set; }
    }
}
