//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Bureau
    {
        public Nullable<int> idPays { get; set; }
        public Nullable<int> idRegion { get; set; }
        public Nullable<int> idGouvernorat { get; set; }
        public Nullable<int> idOrganisation { get; set; }
        public Nullable<int> idDelegation { get; set; }
        public Nullable<int> idBatiment { get; set; }
        public int Id_etage { get; set; }
        public int Id_bureau { get; set; }
        public Nullable<int> Code_a_barre { get; set; }
        public string Description { get; set; }
        public int id { get; set; }
        public Nullable<int> Id_direction { get; set; }
    
        public virtual Etage Etage { get; set; }
    }
}
