//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
  

    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;

    public partial class Delegation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delegation()
        {
            this.Batiment = new HashSet<Batiment>();
            this.Depot = new HashSet<Depot>();
            this.Fournisseur = new HashSet<Fournisseur>();
            this.Societe_maintenance = new HashSet<Societe_maintenance>();
            this.Societe_assurance = new HashSet<Societe_assurance>();
        }
    
        public int idPays { get; set; }
        public int idRegion { get; set; }
        public int idGouvernorat { get; set; }
        
        [DataType(DataType.Currency)]
        public int idDelegation { get; set; }
        [StringLength(10, MinimumLength = 4, ErrorMessage = "Champ invalide")]
        [RegularExpression(@"^[a-zA-Z 0-9]+$", ErrorMessage = "Le nom de la délégation est invalide")]  
        public string libelle { get; set; }
        [RegularExpression(@"[\d]{4}", ErrorMessage = "Le code postal est incorrect : il doit comprendre 4 chiffres")]
        public Nullable<int> Code_postal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batiment> Batiment { get; set; }
        public virtual Gouvernorat Gouvernorat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Depot> Depot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fournisseur> Fournisseur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Societe_maintenance> Societe_maintenance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Societe_assurance> Societe_assurance { get; set; }
    }
}
