//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Etage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etage()
        {
            this.Bien = new HashSet<Bien>();
            this.Bureau = new HashSet<Bureau>();
        }
    
        public Nullable<int> idDelegation { get; set; }
        public int idBatiment { get; set; }
        public int Id_etage { get; set; }
        [Required(ErrorMessage = "Le code de l'étage est obligatoire")]
        [StringLength(10, MinimumLength = 1, ErrorMessage = "Le code de l'étage doit contenir au minimum 1 caractères")]
        [RegularExpression(@"^[a-zA-Z 0-9éèêâùÉÈ-]+$", ErrorMessage = "Le code de l'étage est invalide.Exemple: 01")]
        public string code { get; set; }
        [Required(ErrorMessage = "La description est obligatoire")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "La description doit contenir au minimum 3 caractères")]
        [RegularExpression(@"^[a-zA-Z 0-9éèêâùÉÈ]+$", ErrorMessage = "La description est invalide.Exemple: étage 1")]
        public string description { get; set; }
        [Required(ErrorMessage = "Le code à barre est obligatoire")]
        [StringLength(13, MinimumLength = 13, ErrorMessage = "Le code à barre est invalide : il doit contenir 13 chiffres")]
        [RegularExpression(@"^[0-9]+$+$", ErrorMessage = "Le code à barre est invalide")]
        public string code_a_barre { get; set; }
    
        public virtual Batiment Batiment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bien> Bien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bureau> Bureau { get; set; }
    }
}
