//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Inventaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventaire()
        {
            this.InventaireBien = new HashSet<InventaireBien>();
            this.InventaireVehicule = new HashSet<InventaireVehicule>();
        }
    
        public int Id_inventaire { get; set; }
        [Required(ErrorMessage = "Le nom de l'inventaire est obligatoire")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Le nom de l'inventaire  doit comporter entre 2 et 30 caractéres")]
        [RegularExpression(@"^[a-zA-Z 0-9éèêâùÉÈ]+$", ErrorMessage = "Le nom de l'inventaire est invalide")]
        public string Nom_ { get; set; }
        [Required(ErrorMessage = "Le type de l'inventaire est obligatoire")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Le type de la governorat doit comporter entre 2 et 30 caractéres")]
        [RegularExpression(@"^[a-zA-Z 0-9éèêâùÉÈ]+$", ErrorMessage = "Le type de la governorat est invalide")]
        public string Type { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "La date est obligatoire")]
        public Nullable<System.DateTime> Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventaireBien> InventaireBien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventaireVehicule> InventaireVehicule { get; set; }
    }
}
