//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marque
    {
        public Nullable<int> Id_categorie { get; set; }
        public Nullable<int> id_sous_categorie { get; set; }
        public Nullable<int> IdModele { get; set; }
        public int Id_sous_Modele { get; set; }
        public int IdMarque { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
    
        public virtual Sous_modele Sous_modele { get; set; }
    }
}
