//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Modele
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modele()
        {
            this.Sous_modele = new HashSet<Sous_modele>();
        }
    
        public Nullable<int> Id_categorie { get; set; }
        public int id_sous_categorie { get; set; }
        public int IdModele { get; set; }
        [Required(ErrorMessage = "Le modéle est obligatoire")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "Le modéle doit comporter entre 2 et 30 caractéres")]
        [RegularExpression(@"^[a-zA-Z 0-9éèêâùÉÈ]+$", ErrorMessage = "Le modéle est invalide")]
        public string libelle { get; set; }
    
        public virtual Sous_categorie Sous_categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sous_modele> Sous_modele { get; set; }
    }
}
