//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.Bien = new HashSet<Bien>();
            this.Bureau = new HashSet<Bureau>();
            this.Utilisateur = new HashSet<Utilisateur>();
        }
    
        public Nullable<int> Id_direction { get; set; }
        public int Id_service { get; set; }
        public int id_pers { get; set; }
        public int Rol_id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<int> Matricule { get; set; }
        public string Email { get; set; }
        public Nullable<int> Num_tel { get; set; }
        public string CIN { get; set; }
        public Nullable<System.DateTime> Date_anniv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bien> Bien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bureau> Bureau { get; set; }
        public virtual Role Role { get; set; }
        public virtual ServiceD ServiceD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilisateur> Utilisateur { get; set; }
    }
}
