//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sous_categorie
    {
        public int Id_categorie { get; set; }
        public int id_categorie_Designation { get; set; }
        public int IdSousCategorie { get; set; }
        public string libelle { get; set; }
    
        public virtual CategorieDesignation CategorieDesignation { get; set; }
    }
}
