//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trace
    {
        public int Id_Trace { get; set; }
        public string Users { get; set; }
        public string Actions { get; set; }
        public string Tables { get; set; }
        public string Champs { get; set; }
        public Nullable<System.DateTime> Dates { get; set; }
    }
}
