//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Vehicule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicule()
        {
            this.MouvementVehicule = new HashSet<MouvementVehicule>();
        }
    
        public Nullable<int> idPays { get; set; }
        public Nullable<int> idRegion { get; set; }
        public Nullable<int> idGouvernorat { get; set; }
        public Nullable<int> idOrganisation { get; set; }
        public Nullable<int> idDelegation { get; set; }
        public Nullable<int> idBatiment { get; set; }
        public int Id_parc { get; set; }
        public int Id_Vehicule { get; set; }
        public Nullable<int> Id_achat { get; set; }
        [Required(ErrorMessage = "La matricule est obligatoire")]
        [StringLength(10, MinimumLength = 6, ErrorMessage = "La matricule doit contenir au maximum 10 caractéres")]
        [RegularExpression(@"^([0-9]{2,3})+([TUN|tun]{1})+([0-9]{1,4})+$", ErrorMessage = "La matricule est invalide.Exemple: 117TUN2016")]
        public string Matricule { get; set; }
        [Required(ErrorMessage = "Le modèle est obligatoire")]
        [StringLength(15, MinimumLength = 2, ErrorMessage = "Le modèle doit contenir au minimum 2 caractéres")]
        [RegularExpression(@"^[a-zA-Z -_' 0-9]+$", ErrorMessage = "Le modèle est invalide.Exemple: CITROEN")]
        public string Modele { get; set; }
        [Required(ErrorMessage = "La designation est obligatoire")]

        public string Etat { get; set; }
        [Required(ErrorMessage = "Le numéro de châssis est obligatoire")]
        [StringLength(17, MinimumLength = 17, ErrorMessage = "Le numéro de châssis doit contenir 17 caractéres")]
        [RegularExpression(@"^[A-Z0-9]+$", ErrorMessage = "Le numéro de châssis est invalide.Exemple: JMZMA18P200411817")]
        public string Num_chassis { get; set; }
        [Required(ErrorMessage = "Le prix d'achat est obligatoire")]
        [RegularExpression(@"[0-9]+([,][0-9]{0,3})?", ErrorMessage = "Le prix d'achat est invalid.Exemlpe: 200000,000")]
        public Nullable<double> Prix_d_achat { get; set; }

        public virtual Achat Achat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MouvementVehicule> MouvementVehicule { get; set; }
        public virtual Parc_auto Parc_auto { get; set; }
    }
}
